language: node_js
branches:
  only:
    - master
    - tests
git:
  depth: 1
node_js:
  - '0.10'
env:
  - SASS_VERSION=3.4.13
before_script:
  - gem update --system
  - gem install sass -v $SASS_VERSION
  - npm install -g grunt-cli
